[theme]
base = "light"

# General color setup
textColor = "#000000"
primaryColor = "#615fff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#97afffff"

# Widgets
showWidgetBorder = true
borderColor = "#7a899cff"

# Dataframes
dataframeHeaderBackgroundColor = "#8fa1c0ff"

# Base text
font = "'Space Grotesk':https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap"
baseFontWeight = 300
baseFontSize = 14

# Heading text
headingFont = "Space Grotesk"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]

[client]
showSidebarNavigation = false

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false
