""" Constants for Automation Agent """

LANGUAGE_JAVA = "java"
LANGUAGE_BASH = "bash"
LANGUAGE_POWERSHELL = "powershell"
LANGUAGE_ANSIBLE = "ansible"

SUPPORTED_LANGUAGES = [LANGUAGE_JAVA, LANGUAGE_BASH, LANGUAGE_POWERSHELL, LANGUAGE_ANSIBLE]
