""" Judge Generated Plan Tool """
import logging
from utils.inference_gateway import InferenceGateway
from utils.settings import settings

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """
    You are an AI Agent whose role is to quality check the implementation plan generated by a competing
    model and confirm that the plan adequately and comrehensively fulfills the user's automation request.
    You will be provided the user's original request as well as IT infrastructure content that describes
    the user's environment for which the automation must cooperate within.

    Your response must include an overall evaluation of the plan, as well as enhancement or modification
    suggestions, if any.  The competing model will be asked to adjust its plan based on your guidance.
"""

async def judge_plan(user_request: str, research: str, nominated_plan: str) -> str:
    """ (Step 3 of 5)  Review the provided implementation plan for an automation generation request for
        accuracy and quality.  The result will be suggestions and criticism, if any, that must be 
        incorporated into the implementation plan.  If the suggested plan is modified based on the
        feedback, it must be re-judged by reinvoking this tool.
    
        user_request - (required) write up for the user's request for automation
        research - (required) helpful research as it relates to implementing the user's automation request
        suggested_plan - nominated implementation plan for the request

        Returns: Quality assessment of the provided parameteres
    """
    logger.info("judge_plan parameters.  User_Request=%s  Research=%s. Nominated_Plan=%s",\
                user_request, research, nominated_plan)

    # validate that all required parameters were provided
    if user_request is None or len(user_request) == 0:
        msg = "ERROR: 'user_request' is a required argument and cannot be empty"
        logger.error(msg)
        return msg
    if research is None or len(research) == 0:
        msg = "ERROR: 'research' is a required argument and cannot be empty"
        logger.error(msg)
        return msg
    if nominated_plan is None or len(nominated_plan) == 0:
        msg = "ERROR: 'nominated_plan' is a required argument and cannot be empty"
        logger.error(msg)
        return msg

    # build user prompt
    prompt = f"""Implementation Plan to Judge:
        {nominated_plan}

        User Request:
        {user_request}

        Context:
        {research}"""

    # execute inference
    gateway = InferenceGateway()
    critical_feedback = gateway.simple_chat(SYSTEM_PROMPT, prompt, settings.JUDGE_PLAN_MODEL)

    logger.info("Critical Feedback: %s", critical_feedback)
    return critical_feedback
